Specify RollingWithNewBatch and batch size 1
Sage-Bionetworks/Agora-infra pull request #105
Opened 2021-08-24 18:50 UTC by xschildw

Change the deployment policy on staging, I think the 30% is from UI so also changed the batch size to fixed 1 (I assume it's ignored if we go back to immutable, the doc is not clear on that).

2021-08-24 19:39 UTC, zaro0508 requested changes

2021-08-24 19:39 UTC, zaro0508 commented on templates/beanstalk.yaml
> +          Value: Fixed
Updating this will update for all envs which I guess means that you need to update all envs to `RollingWithAdditionalBatch`?

It also might be nice to parameterize these.

2021-08-24 19:39 UTC, zaro0508 commented on config/staging/agora.yaml
> +  EbDeploymentPolicy: 'RollingWithAdditionalBatch'
maybe you should update for dev & prod as well?  remember the deployment only happens when you merge the changes into the branches.

2021-08-25 00:23 UTC, xschildw commented on templates/beanstalk.yaml
> +          Value: Fixed
I made the size a parameter, and made both BatchSizeTyope and BatchSize condition on having a roliing update. Given how few instances, I don't think it's necessary to support percentage.

2021-08-25 15:32 UTC, zaro0508 requested changes

2021-08-25 15:32 UTC, zaro0508 commented on templates/beanstalk.yaml
> +          Value: !If [UseRollingDeploymentPolicy, 'Fixed', !Ref AWS::NoValue]
i'm not sure, but I don't think you can set a parameter but give it `NoValue`.  I would definitely test it to make sure.

I can think of two workarounds
1. Changed EbDeploymentPolicy to fixed value, `Rolling`, for all 3 envs
2. Change this template to a jinja template to give you the ability to use conditional logic anywhere in the file.  something like this.. https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/managed-ec2-linux-v2.j2#L271

2021-08-25 15:32 UTC, zaro0508 commented on templates/beanstalk.yaml
> +          Value: !If [UseRollingDeploymentPolicy, !Ref EbDeploymentBatchSize, !Ref AWS::NoValue]
same here

2021-09-01 18:08 UTC, merged